### ISSUE TITLE
feat(attendance_app): move to sql

### ISSUE THREAD

**Issue by 20yuto20** [20yuto20/attendance_app#1]
# Done
## 20240529
- punch_timeテーブルとbreak_timeテーブルを作成
- 

# ToDo

- [ ] work_done.pyにpunch_timeとbreak_timeのロジックを元にしたコードを追加
```
from get_total_break_duration import get_total_break_duration

# ... 他のコード ...

# 稼働時間の計算及び出力
start_time = datetime.strptime(punch_in_value, "%H:%M")
end_time = datetime.strptime(time2, "%H:%M")
time_diff = end_time - start_time
work_hours = time_diff.seconds // 3600
work_minutes = (time_diff.seconds // 60) % 60

# 休憩時間の合計を計算
total_break_hours, total_break_minutes = get_total_break_duration(p_key)

true_work_hours = work_hours - total_break_hours
true_work_minutes = work_minutes - total_break_minutes

# ... 他のコード ...
```
- [ ] punch_timeテーブルのpunch_putカラムにwork_done.pyの`time2`変数をどうにかして適当なロジックを用いて`INSERT`できるようにする
現在考えているロジックは
SELECT構文で`user_id`を元にして、`p_key`の値の最大値を取得してそのレコードのpunch_outカラムに`INSERT`する

- [ ] calculate_break_time.pyの大幅な変更
主な変更としては、休憩ロジックをSQLに移行したことによって生じるロジックの変更
**以下のコードはロジックなどを含めて要検討**
```
import os
from slack_bolt import App
from datetime import datetime
import pyodbc
from db_connection import get_db_connection
from get_total_break_duration import get_total_break_duration

app = App(token=os.environ["SLACK_BOT_TOKEN"])

def handle_break_begin(ack, body, client, logger):
    ack()
    user_id = body["user"]["id"]
    workspace_id = body["user"]["team_id"]
    break_begin_time = datetime.now()

    try:
        # punch_timeテーブルから、該当のユーザーIDと現在の作業時間に対応するp_keyを取得
        connection = get_db_connection()
        cursor = connection.cursor()

        query = "SELECT TOP 1 p_key FROM punch_time WHERE punch_user_id = ? AND punch_workspace_id = ? ORDER BY punch_date DESC, punch_in DESC"
        cursor.execute(query, (user_id, workspace_id))
        result = cursor.fetchone()

        if result:
            punch_id = result.p_key

            # break_timeテーブルに新しいレコードを挿入
            query = "INSERT INTO break_time (punch_id, break_begin_time) VALUES (?, ?)"
            cursor.execute(query, (punch_id, break_begin_time))
            connection.commit()
            logger.info(f"Break started at {break_begin_time} for user {user_id} in workspace {workspace_id}")

            # ユーザーのホームを更新して休憩中のステータスを表示
            try:
                client.views_publish(
                    user_id=user_id,
                    view={
                        "type": "home",
                        "blocks": [
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": "🕒 Kotonaru勤怠管理",
                                    "emoji": True
                                }
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": "勤怠管理アプリへようこそ！こちらでは、日々の業務開始・終了時間、休憩時間の記録が簡単にできます。\n\n*主な機能：*\n- 業務開始・終了の記録\n- 休憩開始・終了の記録\n- 設定のカスタマイズ\n- 勤務時間の統計閲覧"
                                }
                            },
                            {
                                "type": "divider"
                            },
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": "⏱ 勤怠記録",
                                    "emoji": True
                                }
                            },
                            {
                                "type": "actions",
                                "elements": [
                                    {
                                        "type": "button",
                                        "text": {
                                            "type": "plain_text",
                                            "text": "休憩終了",
                                            "emoji": True
                                        },
                                        "style": "danger",
                                        "value": "end_break",
                                        "action_id": "click_break_end"
                                    }
                                ]
                            },
                            {
                                "type": "divider"
                            },
                            {
                                "type": "section",
                                "text": {
                                    "type": "mrkdwn",
                                    "text": f":clock1: *現在のステータス*\n- ステータス: 休憩中\n- 開始時刻: {break_begin_time.strftime('%H:%M')}"
                                }
                            },
                            {
                                "type": "divider"
                            },
                            {
                                "type": "header",
                                "text": {
                                    "type": "plain_text",
                                    "text": "🔧 設定 & 📊 統計",
                                    "emoji": True
                                }
                            },
                            {
                                "type": "actions",
                                "elements": [
                                    {
                                        "type": "button",
                                        "text": {
                                            "type": "plain_text",
                                            "text": "設定",
                                            "emoji": True
                                        },
                                        "value": "open_settings",
                                        "action_id": "open_settings"
                                    },
                                    {
                                        "type": "button",
                                        "text": {
                                            "type": "plain_text",
                                            "text": "統計",
                                            "emoji": True
                                        },
                                        "value": "view_statistics",
                                        "action_id": "view_statistics"
                                    }
                                ]
                            }
                        ]
                    }
                )
            except Exception as e:
                logger.error(f"Error publishing view: {e}")
        else:
            logger.warning(f"No ongoing work session found for user {user_id} in workspace {workspace_id}")

        cursor.close()
        connection.close()

    except Exception as e:
        logger.error(f"Error in handle_break_begin: {e}")

def handle_break_end(ack, body, client, logger):
    ack()
    user_id = body["user"]["id"]
    workspace_id = body["user"]["team_id"]
    break_end_time = datetime.now()

    try:
        # punch_timeテーブルから、該当のユーザーIDと現在の作業時間に対応するp_keyを取得
        connection = get_db_connection()
        cursor = connection.cursor()

        query = "SELECT TOP 1 p_key FROM punch_time WHERE punch_user_id = ? AND punch_workspace_id = ? ORDER BY punch_date DESC, punch_in DESC"
        cursor.execute(query, (user_id, workspace_id))
        result = cursor.fetchone()

        if result:
            punch_id = result.p_key

            # break_timeテーブルから、punch_idが取得したp_keyの値で、break_end_timeがNULLのレコードを取得
            query = "SELECT break_id, break_begin_time FROM break_time WHERE punch_id = ? AND break_end_time IS NULL"
            cursor.execute(query, (punch_id,))
            result = cursor.fetchone()

            if result:
                break_id = result.break_id
                break_begin_time = result.break_begin_time

                # 取得したレコードのbreak_end_timeに現在の日時を設定し、break_durationを計算して更新
                query = "UPDATE break_time SET break_end_time = ?, break_duration = DATEDIFF(second, break_begin_time, ?) WHERE break_id = ?"
                cursor.execute(query, (break_end_time, break_end_time, break_id))
                connection.commit()
                logger.info(f"Break ended at {break_end_time} for user {user_id} in workspace {workspace_id}")

                # 休憩時間の合計を計算
                total_break_hours, total_break_minutes = get_total_break_duration(punch_id)

                # ユーザーのホームを更新して業務中のステータスを表示
                try:
                    client.views_publish(
                        user_id=user_id,
                        view={
                            "type": "home",
                            "blocks": [
                                {
                                    "type": "header",
                                    "text": {
                                        "type": "plain_text",
                                        "text": "🕒 Kotonaru勤怠管理",
                                        "emoji": True
                                    }
                                },
                                {
                                    "type": "section",
                                    "text": {
                                        "type": "mrkdwn",
                                        "text": "勤怠管理アプリへようこそ！こちらでは、日々の業務開始・終了時間、休憩時間の記録が簡単にできます。\n\n*主な機能：*\n- 業務開始・終了の記録\n- 休憩開始・終了の記録\n- 設定のカスタマイズ\n- 勤務時間の統計閲覧"
                                    }
                                },
                                {
                                    "type": "divider"
                                },
                                {
                                    "type": "header",
                                    "text": {
                                        "type": "plain_text",
                                        "text": "⏱ 勤怠記録",
                                        "emoji": True
                                    }
                                },
                                {
                                    "type": "actions",
                                    "elements": [
                                        {
                                            "type": "button",
                                            "text": {
                                                "type": "plain_text",
                                                "text": "業務終了",
                                                "emoji": True
                                            },
                                            "style": "danger",
                                            "value": "end_work",
                                            "action_id": "click_work_end"
                                        },
                                        {
                                            "type": "button",
                                            "text": {
                                                "type": "plain_text",
                                                "text": "休憩開始",
                                                "emoji": True
                                            },
                                            "style": "primary",
                                            "value": "start_break",
                                            "action_id": "click_break_begin"
                                        }
                                    ]
                                },
                                {
                                    "type": "divider"
                                },
                                {
                                    "type": "section",
                                    "text": {
                                        "type": "mrkdwn",
                                        "text": f":clock1: *現在のステータス*\n- ステータス: 業務中\n- 開始時刻: {break_end_time.strftime('%H:%M')}\n- 休憩時間: {total_break_hours}時間{total_break_minutes}分"
                                    }
                                },
                                {
                                    "type": "divider"
                                },
                                {
                                    "type": "header",
                                    "text": {
                                        "type": "plain_text",
                                        "text": "🔧 設定 & 📊 統計",
                                        "emoji": True
                                    }
                                },
                                {
                                    "type": "actions",
                                    "elements": [
                                        {
                                            "type": "button",
                                            "text": {
                                                "type": "plain_text",
                                                "text": "設定",
                                                "emoji": True
                                            },
                                            "value": "open_settings",
                                            "action_id": "open_settings"
                                        },
                                        {
                                            "type": "button",
                                            "text": {
                                                "type": "plain_text",
                                                "text": "統計",
                                                "emoji": True
                                            },
                                            "value": "view_statistics",
                                            "action_id": "view_statistics"
                                        }
                                    ]
                                }
                            ]
                        }
                    )
                except Exception as e:
                    logger.error(f"Error publishing view: {e}")
            else:
                logger.warning(f"No ongoing break found for user {user_id} in workspace {workspace_id}")
        else:
            logger.warning(f"No ongoing work session found for user {user_id} in workspace {workspace_id}")

        cursor.close()
        connection.close()

    except Exception as e:
        logger.error(f"Error in handle_break_end: {e}")
```

- [ ] main.pyの変更
```
from calculate_break_time import handle_break_begin, handle_break_end

# ... 他のコード ...

@app.action("click_break_begin")
def handle_handle_break_begin(ack, body, client, logger):
    ack()
    handle_break_begin(ack, body, client, logger)

@app.action("click_break_end")
def handle_handle_break_end(ack, body, client, logger):
    ack()
    handle_break_end(ack, body, client, logger)

# ... 他のコード ...
```

- [ ] ローカルで実行してデバッグ
- [ ] ローカルでの実行が問題ない場合はデプロイする（データベースをMySQLでそのままいけないかを検討する）

## 余力があれば実装
- [ ] break_timeテーブルとpunch_timeテーブルは動作を軽くするために2ヶ月ごとにデータを自動消去するようにロジックを組む

**Comment by 20yuto20** [comment]
## Add To Do

- [ ] manipulate_sheet.pyのロジックを変更する
具体的には現在timestamp sheetから取得している情報をSQLから取得するようにする
その際に留意すること
- `user_id`を元にして設定からsheetのURLを呼び出してauth.pyに突っ込んでシートを操作する。すなわち、個々人でシートを同定できるようにする
- ロジックとしてはを`user_id`をベースにして`p_key`の最大値を探してそのレコードの値から記載するようにする
- その他のロジックは元の関数やコードをなるべく活用して作成すること

**Comment by 20yuto20** [comment]
- [ ] work_done.pyの業務内容の関数についてSQLに移行

**Comment by 20yuto20** [comment]
- [ ] エラーの解消
```
python -u "/Users/yutokohata/Desktop/Kotonaru_attendance_app/backend/main.py"
(base) yutokohata@yutonoMacBook-Pro Kotonaru_attendance_app % python -u "/Users/yutokohata/Desktop/Kotonaru_attendance_app/backend/main.py"
/Users/yutokohata/anaconda3/lib/python3.11/site-packages/slack/deprecation.py:14: UserWarning: slack package is deprecated. Please use slack_sdk.web/webhook/rtm package instead. For more info, go to https://slack.dev/python-slack-sdk/v3-migration/
  warnings.warn(message)
⚡️ Bolt app is running!
selected_language: japanese
report_channel_id: C06SLNY6WLC
invoice_channel_id: C06SWUR0KFT
database_url: 1wRYqum8G3ueK6_shEAjqJpMuDBLwDOTVrD3gmqUzUUU
SP_SHEET: timestamp
supervisor_user_id: U06BQ0771N1
Error updating variables: 'function' object has no attribute 'execute'
ワークスペースID: T06CFM3R0TA内のユーザーID: U06BQ0771N1の設定値が見つかりませんでした。
Failed to run listener function (error: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'time (punch_user_id, punch_workspace_id, punch_date, punch_in) VALUES ('U06BQ077' at line 1)
Traceback (most recent call last):
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 697, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'time (punch_user_id, punch_workspace_id, punch_date, punch_in) VALUES ('U06BQ077' at line 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yutokohata/Desktop/Kotonaru_attendance_app/backend/main.py", line 182, in handle_record_work_start
    record_work_start(ack, body, client)
  File "/Users/yutokohata/Desktop/Kotonaru_attendance_app/backend/work_begin.py", line 90, in record_work_start
    cursor.execute(query, values)
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 372, in execute
    result = self._cnx.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 102, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yutokohata/anaconda3/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'time (punch_user_id, punch_workspace_id, punch_date, punch_in) VALUES ('U06BQ077' at line 1
```

**Comment by 20yuto20** [comment]
- [ ] SP_SHEETすなわちtimestampの名前を入力する必要がないと思うので、その削除と、それを本当に削除してもコードが成立するかを調査する、**特auth.pyやmanipulate_sheet.pyのようなシート操作についてのファイルは注意すること**

**Comment by 20yuto20** [comment]
- [ ] デプロイに際してdockerを作成する

- `dockerfile`
```
FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
```

- `requirements.txt`
**必要なライブラリはきちんと整理して精査すること**
```
slack_bolt
gspread
oauth2client
pandas
matplotlib
mysql-connector-python
```

- `docker-compose.yml`
```
version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - SLACK_BOT_TOKEN=your_slack_bot_token
      - SLACK_APP_TOKEN=your_slack_app_token
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_db_root_password
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=your_db_user
      - MYSQL_PASSWORD=your_db_password
```

**Comment by 20yuto20** [comment]
- [ ] 画面を変遷しないような仕組みを作成する。
今
```
def update_hometab(client, event, logger):
    try:
        user_id = event["user"]
        #event_time = datetime.fromtimestamp(float(event["event_time"]))
        if isinstance(user_id, str):  # ユーザーIDが文字列の場合のみ実行
            #if user_id not in last_app_home_opened or event_time > last_app_home_opened[user_id]:
                client.views_publish(
...（以下略）
```
**これをイベントタイムをSQLを使用してuse_idごとに処理をする。つまりプログラム上で管理せずに外部管理を行う**

**Comment by 20yuto20** [comment]
- [ ] invoiceの仕組みの構築
- [ ] 言語の対応
- [ ] 統計モーダルのアルゴリズム
- [ ] 画面のUIの洗練
- [ ] ボットのメッセージをもっと見やすく
- [ ] 前回の内容をコピーについてアルゴリズムの作成

**Comment by 20yuto20** [comment]
**将来的な仕様変更**
- [ ] URLのIDをURL入力に変更する
- [ ] 設定の保存がそのまま表示されるようにする
- [ ] 以下の部分を次のように変更する。
```
yuto02618さんが業務を終了しました。
yuto02618さんの業務時間：0時間8分
yuto02618さんの休憩時間：0時間0分
業務内容：テスト
詳細：テストテスト

→
yuto02618さんの業務開始時刻：xx:xx
yuto02618さんの業務終了時刻：xx:xx
yuto02618さんが業務を終了しました。
yuto02618さんの業務時間：0時間8分
yuto02618さんの休憩時間：0時間0分
業務内容：テスト
詳細：テストテスト
```
- [ ] アプリの削除にsudoがないか確認する

**Comment by 20yuto20** [comment]
- [ ] 画面変遷の仕様をSQLで処理するようなロジックを立てる。現在コード内でのロジックになっており、それがバグの原因となっている。
**以下の部分を仕様変更する。**
```
@app.event("app_home_opened")
def update_hometab(client, event, logger):
    try:
        user_id = event["user"]
        # event_time = datetime.fromtimestamp(float(event["event_time"])) # バグが起きた時にコメントアウトする
        if isinstance(user_id, str):  # ユーザーIDが文字列の場合のみ実行
            # if user_id not in last_app_home_opened or event_time > last_app_home_opened[user_id]: # バグが起きた時にコメントアウトする
                client.views_publish(
                    user_id=user_id,
                    view={
```

**Comment by 20yuto20** [comment]
- [ ] デプロイ
**デプロイに際して、注意することは、月額を兎に角抑えること**
手順
**環境構築の図をまずは書いてから行う**
1. `Dockerfile`と`docker-compose.yml`の作成を行う
2. RDSの設定
3. λとAPI Gatewayを設定する

**Comment by 20yuto20** [comment]
- [ ] EC2にMySQLをダウンロード
- [ ] RDSでのMySQLへの接続
- [ ] データベースの作成
`name`: atd_app_db
- [ ] `db_connection.py`の変数を変更する
- [ ] 環境変数の設定
**特にslackのbotのトークンは環境変数に設定すること**
その他コードをクローリングして適宜必要な環境変数を設定すること
- [ ] EC2上でこのbotが常に動いているように設定を行う
具体的な手順は以下の通り
```
Slackアプリを常時稼働させるための方法:

EC2インスタンスを常時稼働させるために、インスタンスの自動起動と自動復旧の設定を行うことをお勧めします。
EC2インスタンスの自動起動は、AWS Management Console または AWS CLI を使用して設定できます。インスタンスが停止した場合に自動的に再起動するように設定します。
また、EC2インスタンスの自動復旧は、Amazon EC2 Auto Scaling グループを使用して設定できます。Auto Scalingグループを作成し、インスタンスの健全性チェックを有効にすることで、インスタンスが異常終了した場合に自動的に新しいインスタンスを起動することができます。
さらに、アプリケーションのデプロイメントと更新を自動化するために、AWS CodePipeline や AWS CodeDeploy を使用することができます。これらのサービスを使用すると、コードの変更を自動的にビルド、テスト、デプロイすることができ、アプリケーションの継続的な運用が可能になります。
```

**適宜必要なデバッグ作業を行い、デプロイが完了できるようにする**
## 納期目安は6/10

**Comment by 20yuto20** [comment]
AWS LambdaとAPIゲートウェイを使用してサーバーレスアーキテクチャを構築し、GitHubレポジトリとの連携を維持する方法を以下に説明します。

1. AWS CodePipelineとAWS CodeBuildを使用して、GitHubレポジトリからのプッシュをトリガーにしてLambda関数を自動的にデプロイするCI/CDパイプラインを設定します。

2. AWS Lambda用のデプロイパッケージを作成します。
   - プロジェクトのルートディレクトリに `lambda_function.py` ファイルを作成し、Lambda関数のエントリーポイントを定義します。
   - `requirements.txt` ファイルに必要なPythonモジュールを記述します。
   - プロジェクトのルートディレクトリで以下のコマンドを実行して、デプロイパッケージを作成します。
     ```
     mkdir package
     pip install --target ./package -r requirements.txt
     cd package
     zip -r ../deployment_package.zip .
     cd ..
     zip -g deployment_package.zip lambda_function.py
     ```

3. AWS Management Consoleから、AWS Lambda関数を作成します。
   - 関数名を指定し、ランタイムにPython 3.8を選択します。
   - 実行ロールには、必要な権限を持つIAMロールを選択または作成します。
   - コードのアップロード方法で「.zipファイルをアップロード」を選択し、作成したデプロイパッケージ（`deployment_package.zip`）をアップロードします。
   - ハンドラには、`lambda_function.lambda_handler`を指定します。

4. Amazon API Gatewayを使用して、REST APIを作成します。
   - リソースとメソッドを定義し、LambdaプロキシリクエストをLambda関数にルーティングするように設定します。
   - APIのエンドポイントURLをSlackアプリの設定で指定します。

5. AWS CodePipelineを使用して、GitHubレポジトリからのプッシュをトリガーにしてLambda関数を自動的にデプロイするCI/CDパイプラインを設定します。
   - CodePipelineを作成し、ソースステージでGitHubレポジトリを選択します。
   - ビルドステージでCodeBuildを使用して、デプロイパッケージを作成するビルドプロジェクトを設定します。
   - デプロイステージで、AWS Lambdaを選択し、Lambda関数を更新するアクションを設定します。

6. GitHubレポジトリにプッシュすると、CodePipelineが自動的にトリガーされ、Lambda関数が更新されます。

7. Slackアプリからのリクエストは、API Gatewayを経由してLambda関数に転送され、処理されます。Lambda関数はSlack APIを使用してレスポンスを返します。

この設定により、GitHubレポジトリへのプッシュをトリガーにしてLambda関数が自動的にデプロイされ、APIゲートウェイを介してSlackボットが実行されるサーバーレスアーキテクチャが実現します。

ただし、この移行にはいくつかの変更が必要です。
- EC2固有の設定（tmuxなど）はLambda関数では使用できません。
- データベース接続や外部サービスとの連携は、Lambda関数の制限とベストプラクティスに従って調整する必要があります。
- Lambda関数のログ出力や監視には、Amazon CloudWatchを使用します。

移行の際は、これらの点を考慮し、必要に応じてコードとインフラストラクチャを適

**Comment by 20yuto20** [comment]
**デプロイで詰まっているところ**
- [ ] secretKey.jsonについてエラーが発生しており、シートの更新ができない。
パスはきちんと取れている。
```
update_month_sheet関数を呼び出します。
/home/ec2-user/app/backend/secretKey.json
エラーが発生しました: No key could be detected.
```
- [ ] メッセージの時刻がおかしい
- EC2インスタンス内の時刻に引っ張られている可能性あり。
- ただ、sqlのレコードはきちんとJSTで取れている。
```
[@yuto02618](https://experiment-ddj1178.slack.com/team/U06BQ0771N1)
 yuto02618さんが業務を開始しました。
業務開始時刻：10:33
[19:35](https://experiment-ddj1178.slack.com/archives/C06SLNY6WLC/p1718102115564729)
@yuto02618
 yuto02618さんが業務を終了しました。
yuto02618さんの業務開始時刻：1900-01-01 10:33:00
yuto02618さんの業務終了時刻：1900-01-01 10:35:00
yuto02618さんの正味の業務時間：0時間2分
yuto02618さんの休憩時間：0時間0分
業務内容：l
詳細：l
```
- [ ] 休憩時刻を打刻しない。
ボタンを押しても反応しないし、画面を変遷させると無理やり変わる、しかし、時刻は打刻されていない。
